### ISSUE TITLE
添加后正常编译没问题，但是正常编译后的包，如果再去逆向就会报错。报错如下

### ISSUE THREAD

**Issue by yanglee0801** [xyxyLiu/AndResM#4]
I: Using Apktool 2.3.3 on app-debug.apk
I: Loading resource table...
Exception in thread "main" brut.androlib.AndrolibException: Could not decode arsc file
	at brut.androlib.res.decoder.ARSCDecoder.decode(ARSCDecoder.java:53)
	at brut.androlib.res.AndrolibResources.getResPackagesFromApk(AndrolibResources.java:741)
	at brut.androlib.res.AndrolibResources.loadMainPkg(AndrolibResources.java:67)
	at brut.androlib.res.AndrolibResources.getResTable(AndrolibResources.java:59)
	at brut.androlib.Androlib.getResTable(Androlib.java:68)
	at brut.androlib.ApkDecoder.setTargetSdkVersion(ApkDecoder.java:228)
	at brut.androlib.ApkDecoder.decode(ApkDecoder.java:118)
	at brut.apktool.Main.cmdDecode(Main.java:164)
	at brut.apktool.Main.main(Main.java:73)
Caused by: java.io.IOException: Expected: 0x001c0001, got: 0x000c0203
	at brut.util.ExtDataInput.skipCheckInt(ExtDataInput.java:48)
	at brut.androlib.res.decoder.StringBlock.read(StringBlock.java:44)
	at brut.androlib.res.decoder.ARSCDecoder.readTablePackage(ARSCDecoder.java:119)
	at brut.androlib.res.decoder.ARSCDecoder.readTableHeader(ARSCDecoder.java:82)
	at brut.androlib.res.decoder.ARSCDecoder.decode(ARSCDecoder.java:48)
	... 8 more

**Comment by yanglee0801** [comment]
我尝试过修改了apktool的执行方法，在资源id判断的地方，也加入了我自己使用的特定的资源id前缀。

**Comment by yanglee0801** [comment]
我尝试过修改了apktool的执行方法，在资源id判断的地方，也加入了我自己使用的特定的资源id前缀。但是还是报同样的错误。希望大大帮忙看看

**Comment by xyxyLiu** [comment]
AndResM会在PackageChunk增加一个LibraryChunk，导致Apktool解析arsc出问题，参考https://github.com/iBotPeaches/Apktool/issues/1990
可以再用AndResM 0.3.0 试试。

**Comment by yanglee0801** [comment]
谢谢。目前使用apktool的版本为2.4.1-cc194d-SNAPSHOT ，AndResM 0.3.0。可以成功。谢谢您了
